// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RadioCab.Models;

#nullable disable

namespace RadioCab.Migrations
{
    [DbContext(typeof(RadioCabContext))]
    partial class RadioCabContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RadioCab.Models.Advertisement", b =>
                {
                    b.Property<int>("AdvertisementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdvertisementId"));

                    b.Property<string>("AdImage")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("AdvertiserId")
                        .HasColumnType("integer");

                    b.Property<string>("AdvertiserType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("AdvertisementId")
                        .HasName("PK__Advertis__C4C7F4CDABFE821A");

                    b.HasIndex("PaymentId");

                    b.ToTable("Advertisement");
                });

            modelBuilder.Entity("RadioCab.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("CityId")
                        .HasName("PK__City__F2D21B76EE74DE0E");

                    b.HasIndex(new[] { "ZipCode" }, "UQ__City__2CC2CDB8172FEFF0")
                        .IsUnique();

                    b.ToTable("City");
                });

            modelBuilder.Entity("RadioCab.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("BusinessLicense")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyLogo")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FaxNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FbrCertificate")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("MembershipId")
                        .HasColumnType("integer");

                    b.Property<string>("RegisterationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("CompanyId")
                        .HasName("PK__Company__2D971CACCA6DF4AA");

                    b.HasIndex("CityId");

                    b.HasIndex("MembershipId");

                    b.HasIndex("UserId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("RadioCab.Models.CompanyFeedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("FeedbackId")
                        .HasName("PK__CompanyF__6A4BEDD6CEF586DF");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyFeedback");
                });

            modelBuilder.Entity("RadioCab.Models.CompanyService", b =>
                {
                    b.Property<int>("CompanyServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CompanyServiceId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("ServiceDescription")
                        .HasColumnType("text");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<bool?>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("CompanyServiceId")
                        .HasName("PK__CompanyS__44FB59A09AB73129");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ServiceId");

                    b.ToTable("CompanyServices");
                });

            modelBuilder.Entity("RadioCab.Models.CompanyVacancy", b =>
                {
                    b.Property<int>("VacancyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VacancyId"));

                    b.Property<string>("AdminRemarks")
                        .HasColumnType("text");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("RequiredExperience")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Salary")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("VacancyId")
                        .HasName("PK__CompanyV__6456763F89BC3FE9");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyVacancy");
                });

            modelBuilder.Entity("RadioCab.Models.ContactRequest", b =>
                {
                    b.Property<int>("ContactRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ContactRequestId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("New");

                    b.Property<int>("TargetId")
                        .HasColumnType("integer");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ContactRequestId")
                        .HasName("PK__ContactR__96BC305FE008A6DE");

                    b.HasIndex("UserId");

                    b.ToTable("ContactRequest");
                });

            modelBuilder.Entity("RadioCab.Models.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DriverId"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("Cnic")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("DriverPhoto")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("DrivingLicenseFile")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("DrivingLicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Experience")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MembershipId")
                        .HasColumnType("integer");

                    b.Property<string>("RegisterationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("VehicleInfo")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("DriverId")
                        .HasName("PK__Driver__F1B1CD04B20C3A57");

                    b.HasIndex("CityId");

                    b.HasIndex("MembershipId");

                    b.HasIndex("UserId");

                    b.ToTable("Driver");
                });

            modelBuilder.Entity("RadioCab.Models.DriverFeedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("FeedbackId")
                        .HasName("PK__DriverFe__6A4BEDD6FDF8474F");

                    b.HasIndex("DriverId");

                    b.ToTable("DriverFeedback");
                });

            modelBuilder.Entity("RadioCab.Models.DriverService", b =>
                {
                    b.Property<int>("DriverServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DriverServiceId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.HasKey("DriverServiceId")
                        .HasName("PK__DriverSe__29A2842642F447D9");

                    b.HasIndex("ServiceId");

                    b.HasIndex(new[] { "DriverId", "ServiceId" }, "UQ_Driver_Service")
                        .IsUnique();

                    b.ToTable("DriverServices");
                });

            modelBuilder.Entity("RadioCab.Models.Faq", b =>
                {
                    b.Property<int>("FaqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FaqId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("FaqId")
                        .HasName("PK__Faq__9C741C4378C6ECFA");

                    b.ToTable("Faq");
                });

            modelBuilder.Entity("RadioCab.Models.Feature", b =>
                {
                    b.Property<int>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FeatureId"));

                    b.Property<string>("FeatureKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("FeatureId")
                        .HasName("PK__Feature__82230BC9828E6353");

                    b.HasIndex(new[] { "FeatureKey" }, "UQ__Feature__FCEFA3304746D133")
                        .IsUnique();

                    b.ToTable("Feature");
                });

            modelBuilder.Entity("RadioCab.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("AdminRemarks")
                        .HasColumnType("text");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FeedbackType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("FeedbackId")
                        .HasName("PK__Feedback__6A4BEDD66C664ECF");

                    b.HasIndex("CityId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("RadioCab.Models.Membership", b =>
                {
                    b.Property<int>("MembershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MembershipId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("MembershipName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MembershipId")
                        .HasName("PK__Membersh__92A786795904E66B");

                    b.ToTable("Membership");
                });

            modelBuilder.Entity("RadioCab.Models.MembershipFeature", b =>
                {
                    b.Property<int>("MembershipFeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MembershipFeatureId"));

                    b.Property<int>("FeatureId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("MaxAmount")
                        .HasColumnType("integer");

                    b.Property<int>("MembershipId")
                        .HasColumnType("integer");

                    b.HasKey("MembershipFeatureId")
                        .HasName("PK__Membersh__CF4CA4D3E13D3438");

                    b.HasIndex("FeatureId");

                    b.HasIndex(new[] { "MembershipId", "FeatureId" }, "UQ__Membersh__1A85B6C4EED665E2")
                        .IsUnique();

                    b.ToTable("MembershipFeature");
                });

            modelBuilder.Entity("RadioCab.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime");

                    b.Property<int>("PaymentAmountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentPurpose")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PaymentScreenshot")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payment__9B556A3832F375B9");

                    b.HasIndex("PaymentAmountId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("UserId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("RadioCab.Models.PaymentAmount", b =>
                {
                    b.Property<int>("PaymentAmountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentAmountId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("DurationInMonths")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("MembershipId")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("PaymentAmountId")
                        .HasName("PK__PaymentA__D1A1FC47E5AAC7ED");

                    b.HasIndex(new[] { "MembershipId", "EntityType", "PaymentType" }, "UQ_PaymentAmount")
                        .IsUnique();

                    b.ToTable("PaymentAmount");
                });

            modelBuilder.Entity("RadioCab.Models.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentMethodId"));

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("PaymentMethodId")
                        .HasName("PK__PaymentM__DC31C1D3E8758A66");

                    b.HasIndex(new[] { "MethodName" }, "UQ__PaymentM__218CFB1759D59EC7")
                        .IsUnique();

                    b.ToTable("PaymentMethod");
                });

            modelBuilder.Entity("RadioCab.Models.PlatformService", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Approved");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("ServiceDescription")
                        .HasColumnType("text");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool?>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("ServiceId")
                        .HasName("PK__Platform__C51BB00AF1088673");

                    b.ToTable("PlatformServices");
                });

            modelBuilder.Entity("RadioCab.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServiceId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsForCompany")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsForDriver")
                        .HasColumnType("boolean");

                    b.Property<string>("ServiceDescription")
                        .HasColumnType("text");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("ServiceId")
                        .HasName("PK__Services__C51BB00A84AA8E3A");

                    b.HasIndex(new[] { "ServiceName" }, "UQ__Services__A42B5F9973C4124C")
                        .IsUnique();

                    b.ToTable("Services");
                });

            modelBuilder.Entity("RadioCab.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("UserID")
                        .HasName("PK__Users__1788CCAC984B90A8");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D1053443CCF8B5")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RadioCab.Models.VacancyApplication", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ApplicationId"));

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("CvFile")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Applied");

                    b.Property<int>("VacancyId")
                        .HasColumnType("integer");

                    b.HasKey("ApplicationId")
                        .HasName("PK__VacancyA__C93A4C99C86FBC7F");

                    b.HasIndex("VacancyId");

                    b.ToTable("VacancyApplication");
                });

            modelBuilder.Entity("RadioCab.Models.Advertisement", b =>
                {
                    b.HasOne("RadioCab.Models.Payment", "Payment")
                        .WithMany("Advertisements")
                        .HasForeignKey("PaymentId")
                        .HasConstraintName("FK_Advertisement_Payment");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("RadioCab.Models.Company", b =>
                {
                    b.HasOne("RadioCab.Models.City", "City")
                        .WithMany("Companies")
                        .HasForeignKey("CityId")
                        .IsRequired()
                        .HasConstraintName("FK_Company_City");

                    b.HasOne("RadioCab.Models.Membership", "Membership")
                        .WithMany("Companies")
                        .HasForeignKey("MembershipId")
                        .IsRequired()
                        .HasConstraintName("FK_Company_Membership");

                    b.HasOne("RadioCab.Models.User", "User")
                        .WithMany("Companies")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Company_User");

                    b.Navigation("City");

                    b.Navigation("Membership");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RadioCab.Models.CompanyFeedback", b =>
                {
                    b.HasOne("RadioCab.Models.Company", "Company")
                        .WithMany("CompanyFeedbacks")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK_CompanyFeedback_Company");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RadioCab.Models.CompanyService", b =>
                {
                    b.HasOne("RadioCab.Models.Company", "Company")
                        .WithMany("CompanyServices")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_company_services_Company");

                    b.HasOne("RadioCab.Models.Service", "Service")
                        .WithMany("CompanyServices")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK_CompanyServices_Service");

                    b.Navigation("Company");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("RadioCab.Models.CompanyVacancy", b =>
                {
                    b.HasOne("RadioCab.Models.Company", "Company")
                        .WithMany("CompanyVacancies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CompanyVacancy_Company");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RadioCab.Models.ContactRequest", b =>
                {
                    b.HasOne("RadioCab.Models.User", "User")
                        .WithMany("ContactRequests")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_ContactRequest_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RadioCab.Models.Driver", b =>
                {
                    b.HasOne("RadioCab.Models.City", "City")
                        .WithMany("Drivers")
                        .HasForeignKey("CityId")
                        .IsRequired()
                        .HasConstraintName("FK_Driver_City");

                    b.HasOne("RadioCab.Models.Membership", "Membership")
                        .WithMany("Drivers")
                        .HasForeignKey("MembershipId")
                        .IsRequired()
                        .HasConstraintName("FK_Driver_Membership");

                    b.HasOne("RadioCab.Models.User", "User")
                        .WithMany("Drivers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Driver_User");

                    b.Navigation("City");

                    b.Navigation("Membership");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RadioCab.Models.DriverFeedback", b =>
                {
                    b.HasOne("RadioCab.Models.Driver", "Driver")
                        .WithMany("DriverFeedbacks")
                        .HasForeignKey("DriverId")
                        .IsRequired()
                        .HasConstraintName("FK_DriverFeedback_Driver");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("RadioCab.Models.DriverService", b =>
                {
                    b.HasOne("RadioCab.Models.Driver", "Driver")
                        .WithMany("DriverServices")
                        .HasForeignKey("DriverId")
                        .IsRequired()
                        .HasConstraintName("FK_DriverServices_Driver");

                    b.HasOne("RadioCab.Models.Service", "Service")
                        .WithMany("DriverServices")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK_DriverServices_Service");

                    b.Navigation("Driver");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("RadioCab.Models.Feedback", b =>
                {
                    b.HasOne("RadioCab.Models.City", "City")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CityId")
                        .IsRequired()
                        .HasConstraintName("FK_Feedback_City");

                    b.Navigation("City");
                });

            modelBuilder.Entity("RadioCab.Models.MembershipFeature", b =>
                {
                    b.HasOne("RadioCab.Models.Feature", "Feature")
                        .WithMany("MembershipFeatures")
                        .HasForeignKey("FeatureId")
                        .IsRequired()
                        .HasConstraintName("FK__Membershi__Featu__71D1E811");

                    b.HasOne("RadioCab.Models.Membership", "Membership")
                        .WithMany("MembershipFeatures")
                        .HasForeignKey("MembershipId")
                        .IsRequired()
                        .HasConstraintName("FK__Membershi__Membe__70DDC3D8");

                    b.Navigation("Feature");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("RadioCab.Models.Payment", b =>
                {
                    b.HasOne("RadioCab.Models.PaymentAmount", "PaymentAmount")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentAmountId")
                        .IsRequired()
                        .HasConstraintName("FK_Payment_Amount");

                    b.HasOne("RadioCab.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodId")
                        .IsRequired()
                        .HasConstraintName("FK_Payment_Method");

                    b.HasOne("RadioCab.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Payment_User");

                    b.Navigation("PaymentAmount");

                    b.Navigation("PaymentMethod");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RadioCab.Models.PaymentAmount", b =>
                {
                    b.HasOne("RadioCab.Models.Membership", "Membership")
                        .WithMany("PaymentAmounts")
                        .HasForeignKey("MembershipId")
                        .IsRequired()
                        .HasConstraintName("FK_PaymentAmount_Membership");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("RadioCab.Models.VacancyApplication", b =>
                {
                    b.HasOne("RadioCab.Models.CompanyVacancy", "Vacancy")
                        .WithMany("VacancyApplications")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VacancyApplication_Vacancy");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("RadioCab.Models.City", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("Drivers");

                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("RadioCab.Models.Company", b =>
                {
                    b.Navigation("CompanyFeedbacks");

                    b.Navigation("CompanyServices");

                    b.Navigation("CompanyVacancies");
                });

            modelBuilder.Entity("RadioCab.Models.CompanyVacancy", b =>
                {
                    b.Navigation("VacancyApplications");
                });

            modelBuilder.Entity("RadioCab.Models.Driver", b =>
                {
                    b.Navigation("DriverFeedbacks");

                    b.Navigation("DriverServices");
                });

            modelBuilder.Entity("RadioCab.Models.Feature", b =>
                {
                    b.Navigation("MembershipFeatures");
                });

            modelBuilder.Entity("RadioCab.Models.Membership", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("Drivers");

                    b.Navigation("MembershipFeatures");

                    b.Navigation("PaymentAmounts");
                });

            modelBuilder.Entity("RadioCab.Models.Payment", b =>
                {
                    b.Navigation("Advertisements");
                });

            modelBuilder.Entity("RadioCab.Models.PaymentAmount", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("RadioCab.Models.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("RadioCab.Models.Service", b =>
                {
                    b.Navigation("CompanyServices");

                    b.Navigation("DriverServices");
                });

            modelBuilder.Entity("RadioCab.Models.User", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("ContactRequests");

                    b.Navigation("Drivers");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
